<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-62EHF2O" failures="1" tests="3" name="Test1" time="9.45" errors="0" timestamp="2025-06-18T22:05:34 IST">
  <testcase classname="com.saucelab.test.TestClass1" name="doLogin" time="3.609"/>
  <testcase classname="com.saucelab.test.TestClass1" name="doLogin" time="3.071"/>
  <testcase classname="com.saucelab.test.FailedTestClass" name="testFail" time="1.715">
    <failure type="java.lang.AssertionError" message="Deliberate fail">
      <![CDATA[java.lang.AssertionError: Deliberate fail
at com.saucelab.test.FailedTestClass.testFail(FailedTestClass.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="com.practice.rough.BaseTest" name="@AfterSuite flushExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite flushExtentReport -->
  <testcase classname="com.practice.rough.BaseTest" name="@BeforeSuite initializeExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite initializeExtentReport -->
</testsuite> <!-- Test1 -->
