<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-62EHF2O" failures="1" tests="3" name="Test1" time="14.621" errors="0" timestamp="2025-06-18T22:08:04 IST">
  <testcase classname="com.saucelab.test.TestClass1" name="doLogin" time="5.837"/>
  <testcase classname="com.saucelab.test.TestClass1" name="doLogin" time="4.588"/>
  <testcase classname="com.saucelab.test.FailedTestClass" name="testFail" time="2.477">
    <failure type="java.lang.AssertionError" message="Deliberate fail">
      <![CDATA[java.lang.AssertionError: Deliberate fail
at com.saucelab.test.FailedTestClass.testFail(FailedTestClass.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="com.practice.rough.BaseTest" name="@AfterSuite flushExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite flushExtentReport -->
  <testcase classname="com.practice.rough.BaseTest" name="@BeforeSuite initializeExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite initializeExtentReport -->
</testsuite> <!-- Test1 -->
